project:
  type: website
  resources:
    - "files/*"

website:
  title: "David Loeb"
  favicon: files/favicon-teal.svg
  navbar:
    logo: files/navbar-logo-teal-2.png
    left:
      - research.qmd
      - software.qmd
      - teaching.qmd
      - href: cv.qmd
        text: "CV"
      - blog.qmd
    search: false
  page-footer: 
    right: 'Built with [{{< iconify simple-icons quarto >}} Quarto](https://quarto.org){target="_blank"}<br>View source on [{{< iconify fa github >}} GitHub](https://github.com/david-loeb/david-loeb.github.io){target="_blank"}'
    background: light

format:
  html:
    theme:
      #light: pulse
      #light: yeti
      light: flatly
      #light: [flatly, themes/flatly-purple.scss]
      #light: [flatly, themes/flatly-blue.scss]
      dark: darkly
      #dark: [darkly, themes/darkly-purple.scss]
    css: styles.css
    respect-user-color-scheme: true



